from pathlib import Path
import json

BASE_DIR = Path("images/gallery/full")
OUTPUT_FILE = Path("js/gallery-data.js")
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".heic"}
HEADER = """// ============================================================
//  GALLERY DATA  (AUTO-GENERATED - DO NOT EDIT BY HAND)
//  Generated by build-gallery.py. Any manual edits here are
//  overwritten the next time the script is run.
//
//  To add photos:
//    1. Put the images in a year folder inside images/gallery/full/
//       (e.g. "2026" or "2021-2025"; create a new folder if needed)
//    2. From the project folder, run: python build-gallery.py
//    3. Commit and push this file together with the new images
//
//  Format (written by the script):
//    year   – name of the year folder (string)
//    images – image paths in that folder (array of strings)
//
//  Year folders are sorted newest first (end year for ranges).
//  Images in a folder are sorted by filename, reverse alphabetical.
//  The home page gallery strip uses home-gallery-data.js instead.
// ============================================================

"""

def is_image(f):
    return f.suffix.lower() in IMAGE_EXTENSIONS

def get_year_sort_key(folder):
    # For ranges like "2021-2025", sort by end year. For "2026", sort by that year.
    parts = folder.name.replace("–", "-").split("-")
    try:
        return int(parts[-1])
    except ValueError:
        return 0

if not BASE_DIR.exists():
    print("Gallery folder not found.")
    exit()

folders = sorted(
    [f for f in BASE_DIR.iterdir() if f.is_dir()],
    key=get_year_sort_key,
    reverse=True
)

gallery_data = []
for folder in folders:
    images = sorted([f for f in folder.iterdir() if is_image(f)], reverse=True)
    if not images:
        continue
    gallery_data.append({
        "year": folder.name,
        "images": [str(img).replace("\\", "/") for img in images]
    })

OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(HEADER)
    f.write("const galleryData = ")
    f.write(json.dumps(gallery_data, indent=4))
    f.write(";\n")

for group in gallery_data:
    print(f"✔ {len(group['images'])} images added from {group['year']}")